config:
    early_stopping: {
        'monitor': 'val_loss',
        'patience': 30,
        'restore_best_weights': True,
        'verbose': 1
      }

    ReduceLROnPlateau: {
        'monitor': 'val_loss',
        'factor': 0.5,
        'patience': 8,
        'min_lr': 1e-7,
        'verbose': 1
      }